[versions]
jgit = "5.12.0.202106070339-r"
konsole = "0.9.0"
kotlinx-cli = "0.3.2"

[libraries]
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
konsole = { module = "com.varabyte:konsole", version.ref = "konsole" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinx-cli" }