[versions]
freemarker = "2.3.31"
jgit = "5.12.0.202106070339-r"
kaml = "0.35.3"
kobweb = "0.3.0-SNAPSHOT"
konsole = "0.9.0-SNAPSHOT"
kotlin = "1.5.30"
kotlinx-cli = "0.3.2"
ksp = "1.5.30-1.0.0"
ktor = "1.6.3"
logback = "1.2.3"
truthish = "0.6.0"

[libraries]
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker"}
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
konsole = { module = "com.varabyte.konsole:konsole", version.ref = "konsole" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinx-cli" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ktor-auth = { module = "io.ktor:ktor-auth", version.ref = "ktor"}
ktor-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor"}
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor"}
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor"}
ktor-server-tests = { module = "io.ktor:ktor-server-tests", version.ref = "ktor"}
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
truthish = { module = "com.varabyte.truthish:truthish", version.ref = "truthish" }

[bundles]
ktor = ["ktor-server-core", "ktor-serialization", "ktor-auth", "ktor-server-host-common", "ktor-server-netty", "logback"]