[versions]
kotlinx-cli = "0.3.2"
konsole = "0.9.0"
jgit = "5.12.0.202106070339-r"

[libraries]
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinx-cli" }
konsole = { module = "com.varabyte:konsole", version.ref = "konsole" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }