# When a release is created, run a Gradle command to create artifacts
# containing the Kobweb binary.

name: release-kobweb-dist

on:
  release:
    types:
      - published

jobs:
  distzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Kobweb CLI artifacts
        run: ./gradlew :cli:kobweb:assembleDist
        
      - uses: actions/upload-artifact@v2
        with:
          path: |
            cli/kobweb/build/distributions/*.zip
            cli/kobweb/build/distributions/*.tar
          if-no-files-found: error
